sonar.organization=parthsanepara
sonar.projectKey=ParthSanepara_hm3301

sonar.projectName=hm3301
sonar.projectVersion=0.1.0

sonar.sources=src/hm3301
sonar.tests=tests
sonar.language=py
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/setup.py,**/conftest.py
sonar.test.inclusions=tests/**/*.py
